insert into FOREIGN_CURRENCY(symbol, name, version) values ('ALL', 'Albania Lek', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('AFN', 'Afghanistan Afghani', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('ARS', 'Argentina Peso', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('AWG', 'Aruba Guilder', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('AUD', 'Australia Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('AZN', 'Azerbaijan New Manat', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('BSD', 'Bahamas Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('BBD', 'Barbados Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('BYR', 'Belarus Ruble', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('BZD', 'Belize Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('BMD', 'Bermuda Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('BOB', 'Bolivia Boliviano', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('BAM', 'Bosnia and Herzegovina Convertible Marka', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('BWP', 'Botswana Pula', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('BGN', 'Bulgaria Lev', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('BRL', 'Brazil Real', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('BND', 'Brunei Darussalam Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('KHR', 'Cambodia Riel', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('CAD', 'Canada Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('KYD', 'Cayman Islands Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('CLP', 'Chile Peso', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('CNY', 'China Yuan Renminbi', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('COP', 'Colombia Peso', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('CRC', 'Costa Rica Colon', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('HRK', 'Croatia Kuna', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('CUP', 'Cuba Peso', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('CZK', 'Czech Republic Koruna', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('DKK', 'Denmark Krone', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('DOP', 'Dominican Republic Peso', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('XCD', 'East Caribbean Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('EGP', 'Egypt Pound', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('SVC', 'El Salvador Colon', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('EEK', 'Estonia Kroon', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('EUR', 'Euro Member Countries', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('FKP', 'Falkland Islands (Malvinas) Pound', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('FJD', 'Fiji Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('GHC', 'Ghana Cedis', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('GIP', 'Gibraltar Pound', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('GTQ', 'Guatemala Quetzal', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('GGP', 'Guernsey Pound', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('GYD', 'Guyana Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('HNL', 'Honduras Lempira', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('HKD', 'Hong Kong Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('HUF', 'Hungary Forint', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('ISK', 'Iceland Krona', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('INR', 'India Rupee', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('IDR', 'Indonesia Rupiah', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('IRR', 'Iran Rial', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('IMP', 'Isle of Man Pound', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('ILS', 'Israel Shekel', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('JMD', 'Jamaica Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('JPY', 'Japan Yen', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('JEP', 'Jersey Pound', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('KZT', 'Kazakhstan Tenge', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('KPW', 'Korea (North) Won', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('KRW', 'Korea (South) Won', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('KGS', 'Kyrgyzstan Som', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('LAK', 'Laos Kip', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('LVL', 'Latvia Lat', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('LBP', 'Lebanon Pound', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('LRD', 'Liberia Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('LTL', 'Lithuania Litas', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('MKD', 'Macedonia Denar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('MYR', 'Malaysia Ringgit', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('MUR', 'Mauritius Rupee', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('MXN', 'Mexico Peso', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('MNT', 'Mongolia Tughrik', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('MZN', 'Mozambique Metical', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('NAD', 'Namibia Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('NPR', 'Nepal Rupee', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('ANG', 'Netherlands Antilles Guilder', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('NZD', 'New Zealand Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('NIO', 'Nicaragua Cordoba', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('NGN', 'Nigeria Naira', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('NOK', 'Norway Krone', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('OMR', 'Oman Rial', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('PKR', 'Pakistan Rupee', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('PAB', 'Panama Balboa', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('PYG', 'Paraguay Guarani', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('PEN', 'Peru Nuevo Sol', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('PHP', 'Philippines Peso', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('PLN', 'Poland Zloty', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('QAR', 'Qatar Riyal', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('RON', 'Romania New Leu', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('RUB', 'Russia Ruble', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('SHP', 'Saint Helena Pound', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('SAR', 'Saudi Arabia Riyal', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('RSD', 'Serbia Dinar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('SCR', 'Seychelles Rupee', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('SGD', 'Singapore Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('SBD', 'Solomon Islands Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('SOS', 'Somalia Shilling', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('ZAR', 'South Africa Rand', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('LKR', 'Sri Lanka Rupee', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('SEK', 'Sweden Krona', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('CHF', 'Switzerland Franc', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('SRD', 'Suriname Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('SYP', 'Syria Pound', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('TWD', 'Taiwan New Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('THB', 'Thailand Baht', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('TTD', 'Trinidad and Tobago Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('TRY', 'Turkey Lira', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('TRL', 'Turkey Lira', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('TVD', 'Tuvalu Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('UAH', 'Ukraine Hryvna', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('GBP', 'United Kingdom Pound', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('USD', 'United States Dollar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('UYU', 'Uruguay Peso', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('UZS', 'Uzbekistan Som', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('VEF', 'Venezuela Bolivar', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('VND', 'Viet Nam Dong', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('YER', 'Yemen Rial', 0)
insert into FOREIGN_CURRENCY(symbol, name, version) values ('ZWD', 'Zimbabwe Dollar', 0)
